### ISSUE TITLE
No Code

### ISSUE THREAD

**Issue by lisni946** [hipster-philology/param-bias#1]
The article "Qualitative Analysis of Semantic Language Models" claimed the code was "openly available" (p.93), but there is no code here. Can it be made public?

**Comment by PonteIneptique** [comment]
It's definitely an oversight from us, we forgot to transfer the code here. We'll do ASAP, cc @sonofmun

**Comment by PonteIneptique** [comment]
We transferred the code, a better readme is coming ;)
We have not access to all the latest version of the code unfortunately, because of the confinment, but we think this should be a good start.

**Comment by lisni946** [comment]
Wonderful – thanks so much!
